/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiralabra;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage ikkuna) {
        ikkuna.setTitle("Hei Maailma!");
        // ikkuna.show();
    }

    public static void main(String[] args) {
        launch(App.class);
    }
}

// package tiralabra;

// public class App {
//     public String getGreeting() {
//         return "Hello World!";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }
